-- step 2
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=/opt/app/oracle/oradata/gjzsptm/archivelog/ VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=gjzsptm' scope=BOTH;

-- step 3
ALTER SYSTEM SET LOG_ARCHIVE_DEST_3='LOCATION=/opt/app/oracle/oradata/gjzsptm/archivelog/lstandby VALID_FOR=(STANDBY_LOGFILES,STANDBY_ROLE) DB_UNIQUE_NAME=gjzsptm' scope=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_3=ENABLE scope=BOTH;

-- step 4
EXECUTE DBMS_LOGSTDBY.BUILD;

-- confirm OK
select * from v$database;

SELECT SESSION_ID, STATE FROM V$LOGSTDBY_STATE;
SELECT SID, SERIAL#, SPID, TYPE FROM V$LOGSTDBY_PROCESS;
SELECT PERCENT_DONE, COMMAND FROM V$LOGMNR_DICTIONARY_LOAD WHERE SESSION_ID = (SELECT SESSION_ID FROM V$LOGSTDBY_STATE);

SELECT APPLIED_TIME, APPLIED_SCN, MINING_TIME, MINING_SCN FROM V$LOGSTDBY_PROGRESS;
SELECT * FROM V$LOGFILE;
SELECT * FROM V$ARCHIVED_LOG;
show parameters LOG_ARCHIVE_DEST_;
select name,open_mode,database_role,protection_mode from v$database;

-- fix
SELECT MAX(SEQUENCE#), THREAD# FROM V$ARCHIVED_LOG WHERE RESETLOGS_CHANGE# = (SELECT MAX(RESETLOGS_CHANGE#) FROM V$ARCHIVED_LOG) GROUP BY THREAD#
SELECT DESTINATION, STATUS, ARCHIVED_THREAD#, ARCHIVED_SEQ# FROM V$ARCHIVE_DEST_STATUS WHERE STATUS <> 'DEFERRED' AND STATUS <> 'INACTIVE';
ALTER SYSTEM SWITCH LOGFILE;