-- step 1
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE CANCEL;

-- step 5
SELECT open_mode FROM V$DATABASE;
--ALTER DATABASE MOUNT;
SHUTDOWN IMMEDIATE;
ALTER DATABASE RECOVER TO LOGICAL STANDBY lstandby;

-- step 6
SHUTDOWN;
STARTUP MOUNT;
show parameters LOG_ARCHIVE_DEST_;
show parameters LOG_ARCHIVE_DEST_STATE;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=/opt/app/oracle/oradata/standby/lsarchivelog/ VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=standby' scope=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_1=ENABLE scope=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_3='LOCATION=/opt/app/oracle/oradata/standby/lstandbyarchivelog/ VALID_FOR=(STANDBY_LOGFILES,STANDBY_ROLE) DB_UNIQUE_NAME=standby' scope=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_3=ENABLE scope=BOTH;

-- step 7
ALTER DATABASE OPEN RESETLOGS;
ALTER DATABASE START LOGICAL STANDBY APPLY IMMEDIATE;

-- confirm OK
select * from v$database;

SELECT SESSION_ID, STATE FROM V$LOGSTDBY_STATE;
SELECT SID, SERIAL#, SPID, TYPE FROM V$LOGSTDBY_PROCESS;
SELECT PERCENT_DONE, COMMAND FROM V$LOGMNR_DICTIONARY_LOAD WHERE SESSION_ID = (SELECT SESSION_ID FROM V$LOGSTDBY_STATE);

SELECT APPLIED_TIME, APPLIED_SCN, MINING_TIME, MINING_SCN FROM V$LOGSTDBY_PROGRESS;
SELECT * FROM V$LOGFILE;
SELECT * FROM V$ARCHIVED_LOG;
select name,open_mode,database_role,protection_mode from v$database;

-- fix
ALTER DATABASE GUARD STANDBY;
ALTER SESSION DISABLE GUARD;
ALTER SESSION ENABLE GUARD;
ALTER DATABASE STOP LOGICAL STANDBY APPLY;
ALTER DATABASE START LOGICAL STANDBY APPLY IMMEDIATE;