select * from v$instance;

show parameter instance_name
show parameter SERVICE_NAMES
show parameter LOCAL_LISTENER

ALTER DATABASE RECOVER MANAGED STANDBY DATABASE CANCEL;

-- ALTER DATABASE OPEN;

-- ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE;

ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT;

ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE DISCONNECT;

ALTER SESSION SYNC WITH PRIMARY;

select * from v$database;

SELECT open_mode FROM V$DATABASE;

SELECT * FROM V$STANDBY_EVENT_HISTOGRAM WHERE NAME = 'apply lag' AND COUNT > 0 order by last_time_updated desc;

select * from V$DATAGUARD_STATS;

select * from V$DATAGUARD_CONFIG;

select * from V$MANAGED_STANDBY;

select * from V$DATAGUARD_STATUS;

-- ARCHIVE LOGS

select * from V$ARCHIVE_DEST;

select * from V$ARCHIVE_GAP;

select * from V$ARCHIVED_LOG;

