-- 更改附件名称字段长度
ALTER TABLE ASMS_ROUTINE_MONITOR MODIFY (RM_FILE_NAME VARCHAR2(512));
ALTER TABLE ASMS_SPECIAL_MONITOR MODIFY (SM_FILE_NAME VARCHAR2(512));
ALTER TABLE ASMS_CHECK_TASK MODIFY (ATTACHMENT_NAME VARCHAR2(512));
ALTER TABLE ASMS_EMERGENCY_TASK MODIFY (FILES_NAME VARCHAR2(512));
ALTER TABLE ASMS_INSPECTION_TASK MODIFY (ATTACHMENT_NAME VARCHAR2(512));
ALTER TABLE ASMS_BASE_INSPECTION MODIFY (VIDEO_NAME VARCHAR2(512));
ALTER TABLE ASMS_BASE_INSPECTION MODIFY (HEAD_SIGN_FILE_NAME VARCHAR2(512));
ALTER TABLE ASMS_BASE_INSPECTION MODIFY (INSPECTION_IMAGES_NAME VARCHAR2(2048));
ALTER TABLE ASMS_SUBJ_ENT_TEMP MODIFY (ATTACHMENT_NAME VARCHAR2(512));
