#!/usr/bin/env zsh

kill-session(){
	db_name=${1:?"Please specify db_name"}

	NLS_LANG="SIMPLIFIED CHINESE_CHINA.UTF8" sqlplus64 "sys/Oe123qwe###@10.0.52.1/orcl as sysdba" <<EOI
	alter system kill session $db_name;
	quit
	EOI
}

query-session(){
	user_name=${1:?You must specify db username}
	NLS_LANG="SIMPLIFIED CHINESE_CHINA.UTF8" sqlplus64 "sys/Oe123qwe###@10.0.52.1/orcl as sysdba" <<EOI | egrep '[[:digit:]]+,[[:digit:]]+'
	select sid || ',' || serial# from v\$session where USERNAME='$user_name';
	quit
	EOI
}

query(){
	#set headsep off
	sqlplus64 -S gjzspt/12345678@192.168.21.249/gjzs <<-EOI >/dev/null
	set colsep ','
	set echo off
	set feedback off
	set linesize 1000
	set pagesize 1000
	set sqlprompt ''
	set trimspool on

	spool t.csv

	SELECT * FROM (
	SELECT M.*,ROWNUM as rn FROM
	(SELECT
	T.ID,T.UPDATE_TIME, T.RESOURCE_DIRECTORY_ID, TD.NAME AS RESOURCE_DIR_NAME, T.WEB_SERVICE_ID,
	T.WEB_SERVICE_NAME, T.METHOD_NAME,
	T.CALLER_USER, T.ERROR_TYPE, T.ERROR_DESC,
	T.ERROR_DATE, T.CREATE_BY, T.CREATE_TIME,
	T.UPDATE_BY
	FROM T_DGAP_WS_ERROR_LOG T
	LEFT JOIN T_DGAP_RESOURCE_DIRECTORY TD ON T.RESOURCE_DIRECTORY_ID = TD.ID
	WHERE T.DEL_FLAG = 'N'
	ORDER BY T.UPDATE_TIME DESC
	) M )
	WHERE rn BETWEEN 1+10*0 AND 10*1;

	spool off
	EOI
}

create-schema(){
	db_name=${1:?Please specify db_name}

	NLS_LANG="SIMPLIFIED CHINESE_CHINA.UTF8" sqlplus64 "sys/Oe123qwe###@10.0.52.1/orcl as sysdba" <<EOI
	drop user $db_name cascade;
	create user $db_name identified by 12345678;
	grant connect to $db_name;
	grant resource to $db_name;
	grant create view to $db_name;
	quit
	EOI
}
