                     object_name object_type
                         Test_11       TABLE
             T_SCLTXXCJ_REGISTER       TABLE
               T_SCLTXXCJ_ENTITY       TABLE
                 T_SCLTXXCJ_BASE       TABLE
               T_MDM_BASIC_CODES       TABLE
                T_MDM_BASIC_CODE       TABLE
                   T_DGAP_WS_LOG       TABLE
             T_DGAP_WS_ERROR_LOG       TABLE
            T_DGAP_WS_DAILY_STAT       TABLE
       T_DGAP_TB_RESOURCE_CONFIG       TABLE
            T_DGAP_ROLE_RESOURCE       TABLE
       T_DGAP_RESOURCE_DIRECTORY       TABLE
     T_DGAP_RESOURCE_APPLICATION       TABLE
                 T_DGAP_RESOURCE       TABLE
        T_DGAP_DATA_IMPORT_TABLE       TABLE
        T_DGAP_DATA_IMPORT_FIELD       TABLE
            T_DGAP_ALERT_RECEIPT       TABLE
                T_DGAP_ALERT_LOG       TABLE
             T_DGAP_ALERT_CONFIG       TABLE
                   TTS_TEMP_XSJL       TABLE
               TTS_SCLTXXCJ_XSTH       TABLE
             TTS_SCLTXXCJ_XSDJJL       TABLE
               TTS_SCLTXXCJ_XSDJ       TABLE
  TTS_SCLTXXCJ_USER_CHANGERECORD       TABLE
         TTS_SCLTXXCJ_USERNUMBER       TABLE
               TTS_SCLTXXCJ_USER       TABLE
       TTS_SCLTXXCJ_SLA_PURCHASE       TABLE
     TTS_SCLTXXCJ_SLAUGHTER_STOR       TABLE
  TTS_SCLTXXCJ_SLAUGHTER_SRECORD       TABLE
     TTS_SCLTXXCJ_SLAUGHTER_SALE       TABLE
   TTS_SCLTXXCJ_SLAUGHTER_RECORD       TABLE
     TTS_SCLTXXCJ_SLAUGHTER_PCHC       TABLE
               TTS_SCLTXXCJ_SCGL       TABLE
           TTS_SCLTXXCJ_REGISTER       TABLE
           TTS_SCLTXXCJ_PROPOSAL       TABLE
       TTS_SCLTXXCJ_PRODUCT_TYPE       TABLE
     TTS_SCLTXXCJ_PRODUCTYPENAME       TABLE
  TTS_SCLTXXCJ_PRODUCTION_MANAGE       TABLE
            TTS_SCLTXXCJ_PRODUCT       TABLE
       TTS_SCLTXXCJ_NOTIFICATION       TABLE
             TTS_SCLTXXCJ_ENTITY       TABLE
           TTS_SCLTXXCJ_CUSTOMER       TABLE
             TTS_SCLTXXCJ_CPPCHC       TABLE
          TTS_SCLTXXCJ_COMPLAINT       TABLE
               TTS_SCLTXXCJ_CGGL       TABLE
                    TEST_TEACHER       TABLE
                    TEST_STUDENT       TABLE
                         TEST_SC       TABLE
                     TEST_COURSE       TABLE
                       TEMP_DEMO       TABLE
                   TEMPRORY_DEMO       TABLE
                  TASK_SCHEDULER       TABLE
                      TASK_GROUP       TABLE
                   TASK_FIRE_LOG       TABLE
                   SYS_USER_ROLE       TABLE
                        SYS_USER       TABLE
                    SYS_TEMPLATE       TABLE
                  SYS_RULE_CLASS       TABLE
                   SYS_ROLE_MENU       TABLE
                        SYS_ROLE       TABLE
                    SYS_RESOURCE       TABLE
                      SYS_REGION       TABLE
                        SYS_POST       TABLE
                SYS_ORGANIZATION       TABLE
                 SYS_OPERATE_LOG       TABLE
               SYS_NOTICERELEASE       TABLE
                        SYS_MENU       TABLE
                   SYS_FLOW_NODE       TABLE
                  SYS_FLOW_ACTER       TABLE
                        SYS_FLOW       TABLE
                   SYS_DICT_TYPE       TABLE
                   SYS_DICT_DATA       TABLE
                        SYS_DEPT       TABLE
             SYS_CODE_RULE_FIELD       TABLE
              SYS_CODE_RULE_DATA       TABLE
                   SYS_CODE_RULE       TABLE
                SYS_ARGI_PRODUCT       TABLE
                   QRTZ_TRIGGERS       TABLE
           QRTZ_SIMPROP_TRIGGERS       TABLE
            QRTZ_SIMPLE_TRIGGERS       TABLE
            QRTZ_SCHEDULER_STATE       TABLE
        QRTZ_PAUSED_TRIGGER_GRPS       TABLE
                      QRTZ_LOCKS       TABLE
                QRTZ_JOB_DETAILS       TABLE
             QRTZ_FIRED_TRIGGERS       TABLE
              QRTZ_CRON_TRIGGERS       TABLE
                      PLAN_TABLE       TABLE
                        OA_LEAVE       TABLE
                      DBCOPYTEST       TABLE
             ASMS_SUBJ_SV_REVOKE       TABLE
             ASMS_SUBJ_SV_CHANGE       TABLE
             ASMS_SUBJ_SV_CANCEL       TABLE
             ASMS_SUBJ_SUPERVISE       TABLE
              ASMS_SUBJ_ENT_TEMP       TABLE
         ASMS_SUBJ_ENT_BADRECORD       TABLE
           ASMS_SUBJ_ENFORCE_LAW       TABLE
             ASMS_SUBJ_EL_REVOKE       TABLE
             ASMS_SUBJ_EL_CHANGE       TABLE
             ASMS_SUBJ_EL_CANCEL       TABLE
             ASMS_SUBJ_DT_REVOKE       TABLE
             ASMS_SUBJ_DT_CHANGE       TABLE
             ASMS_SUBJ_DT_CANCEL       TABLE
             ASMS_SUBJ_DETECTION       TABLE
            ASMS_SPECIAL_MONITOR       TABLE
          ASMS_SPECIAL_LEAD_UNIT       TABLE
            ASMS_ROUTINE_MONITOR       TABLE
          ASMS_ROUTINE_LEAD_UNIT       TABLE
               ASMS_RECHECK_TASK       TABLE
             ASMS_RECHECK_OBJECT       TABLE
             ASMS_MONITOR_OBJECT       TABLE
            ASMS_INSPECTION_TASK       TABLE
          ASMS_INSPECTION_ASSESS       TABLE
             ASMS_EMERGENCY_TASK       TABLE
           ASMS_EMERGENCY_EXPERT       TABLE
          ASMS_CHECK_TASK_REPORT       TABLE
                 ASMS_CHECK_TASK       TABLE
            ASMS_CHECK_BEAR_UNIT       TABLE
                  ASMS_BASE_USER       TABLE
            ASMS_BASE_INSPECTION       TABLE
             ALES_WT_TASK_SAMPLE       TABLE
                ALES_TASK_SAMPLE       TABLE
                     ALES_SAMPLE       TABLE
       ALES_PRODUCE_ADMIN_PUNISH       TABLE
             ALES_ENTRUST_SAMPLE       TABLE
          ALES_ENTRUST_DETECTION       TABLE
          ALES_DAILY_ENFORCE_LAW       TABLE
                 ALEMBIC_VERSION       TABLE
                      ADS_RECIPE       TABLE
                  ADS_ORGAN_TASK       TABLE
                ADS_MONITOR_TASK       TABLE
              ADS_MONITOR_SAMPLE       TABLE
                  ADS_MODEL_TYPE       TABLE
           ADS_MODEL_SAMPLE_LINK       TABLE
   ADS_MODEL_OBJECT_ITEM_MAPPING       TABLE
        ADS_MODEL_JUDGE_STANDARD       TABLE
        ADS_MODEL_CHECK_STANDARD       TABLE
          ADS_MODEL_CHECK_OBJECT       TABLE
            ADS_MODEL_CHECK_ITEM       TABLE
     ADS_MODEL_ATTRIBUTE_MAPPING       TABLE
                ADS_INFO_PROJECT       TABLE
                        ADS_FILE       TABLE
               ADS_CHECK_PROJECT       TABLE
                 ADS_CHECK_MODEL       TABLE
                  ADS_CHECK_INFO       TABLE
                 ACT_RU_VARIABLE       TABLE
                     ACT_RU_TASK       TABLE
                      ACT_RU_JOB       TABLE
             ACT_RU_IDENTITYLINK       TABLE
                ACT_RU_EXECUTION       TABLE
             ACT_RU_EVENT_SUBSCR       TABLE
                  ACT_RE_PROCDEF       TABLE
                    ACT_RE_MODEL       TABLE
               ACT_RE_DEPLOYMENT       TABLE
                     ACT_ID_USER       TABLE
               ACT_ID_MEMBERSHIP       TABLE
                     ACT_ID_INFO       TABLE
                    ACT_ID_GROUP       TABLE
                  ACT_HI_VARINST       TABLE
                 ACT_HI_TASKINST       TABLE
                 ACT_HI_PROCINST       TABLE
             ACT_HI_IDENTITYLINK       TABLE
                   ACT_HI_DETAIL       TABLE
                  ACT_HI_COMMENT       TABLE
               ACT_HI_ATTACHMENT       TABLE
                  ACT_HI_ACTINST       TABLE
                 ACT_GE_PROPERTY       TABLE
                ACT_GE_BYTEARRAY       TABLE
