galaxy_info:
  author: Adam Medziński
  description: Oracle JDK Ansible role

  license: license (Apache)

  min_ansible_version: 2.0

  platforms:
  - name: EL
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags:
    - development
    - system

dependencies: []
