.phony: dgapTables249

gjzsptTables249:
	R -e 'source("x.R")' -e 'gjzsptTables249' -e 'fcloseCon()'

wslog:
	R -e 'source("x.R")' -e 'wslog' -e 'fcloseCon()'

exportGjzsptTables:
	R -e 'source("x.R")' -e 'exportGjzsptTables(gjzspt249)' -e 'fcloseCon()'
