--------------------------------------------------------
--  文件已创建 - 星期三-十月-26-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence OA_LEAVE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "GJZSPT"."OA_LEAVE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table T_DGAP_ALERT_CONFIG
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" 
   (	"ID" VARCHAR2(64 BYTE), 
	"ALERT_TYPE" VARCHAR2(10 BYTE), 
	"TARGET_ID" VARCHAR2(64 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"THRESHOLD" NUMBER, 
	"NEED_SEND_ALERT" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."ALERT_TYPE" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."TARGET_ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."DESCRIPTION" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."THRESHOLD" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."NEED_SEND_ALERT" IS '非空，默认值为Y （可填的Y或者N）';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_CONFIG"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
 
   COMMENT ON TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG"  IS '配置需要监控的预警项，包括预警目标、类型、状态等内容';
--------------------------------------------------------
--  DDL for Table T_DGAP_ALERT_LOG
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_ALERT_LOG" 
   (	"ID" VARCHAR2(64 BYTE), 
	"ALERT_CONFIG_ID" VARCHAR2(64 BYTE), 
	"TARGET_ID" VARCHAR2(64 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"ALERT_DATE" DATE, 
	"SOLVE_DATE" DATE, 
	"SOLVE_USER_ID" VARCHAR2(64 BYTE), 
	"SOLVE_STATUS" VARCHAR2(10 BYTE), 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."ALERT_CONFIG_ID" IS '非空，无默认值
预警配置表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."TARGET_ID" IS '非空，无默认值
资源表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."DESCRIPTION" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."ALERT_DATE" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."SOLVE_DATE" IS '可为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."SOLVE_USER_ID" IS '可为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."SOLVE_STATUS" IS '可为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_LOG"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
 
   COMMENT ON TABLE "GJZSPT"."T_DGAP_ALERT_LOG"  IS '记录预警日志';
--------------------------------------------------------
--  DDL for Table T_DGAP_ALERT_RECEIPT
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT" 
   (	"ID" VARCHAR2(64 BYTE), 
	"ALERT_ID" VARCHAR2(64 BYTE), 
	"RECEIPT_BY" VARCHAR2(64 BYTE), 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_RECEIPT"."ID" IS '非空无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_RECEIPT"."ALERT_ID" IS '非空，无默认值
预警配置表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_RECEIPT"."RECEIPT_BY" IS '非空无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_RECEIPT"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_RECEIPT"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_RECEIPT"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_RECEIPT"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ALERT_RECEIPT"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
 
   COMMENT ON TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT"  IS '预警配置全部接收者的表';
--------------------------------------------------------
--  DDL for Table T_DGAP_RESOURCE
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_RESOURCE" 
   (	"ID" VARCHAR2(64 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"TYPE" VARCHAR2(10 BYTE), 
	"DIRECTORY_ID" VARCHAR2(64 BYTE), 
	"DESCRIPTION" VARCHAR2(300 BYTE), 
	"WSDL_URL" VARCHAR2(100 BYTE), 
	"FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."NAME" IS '非空，无默认值，唯一约束';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."TYPE" IS '非空，无默认值 WS: webservcie';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."DIRECTORY_ID" IS '非空，无默认值
资源目录表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."DESCRIPTION" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."WSDL_URL" IS '非空，无默认值
说明webservice如何使用
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."FLAG" IS '非空，默认为Y
N: 不启用 
Y：启用
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
 
   COMMENT ON TABLE "GJZSPT"."T_DGAP_RESOURCE"  IS '记录资源的本身属性及相关描述信息，包括资源名称、资源类型、所属资源目录等信息';
--------------------------------------------------------
--  DDL for Table T_DGAP_RESOURCE_APPLICATION
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" 
   (	"ID" VARCHAR2(64 BYTE), 
	"RESOURCE_ID" VARCHAR2(64 BYTE), 
	"USER_ID" VARCHAR2(64 BYTE), 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT 'NEW', 
	"EFFECTIVE_DATE" DATE, 
	"EXPIRE_DATE" DATE, 
	"REASON" VARCHAR2(200 BYTE), 
	"AUDIT_USER_ID" VARCHAR2(64 BYTE), 
	"PASS_OR_NOT" VARCHAR2(10 BYTE), 
	"APPROVAL" VARCHAR2(50 BYTE), 
	"CONTACT_NUMBER" VARCHAR2(20 BYTE), 
	"CALLER_TOKEN" VARCHAR2(64 BYTE), 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."RESOURCE_ID" IS '非空，无默认值
资源表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."USER_ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."STATUS" IS '非空，默认值NEW
NEW: 待审批
APPR：审批通过
DENY：审批打回
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."EFFECTIVE_DATE" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."EXPIRE_DATE" IS '允许为空
NULL:为空表示不失效
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."REASON" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."AUDIT_USER_ID" IS '允许为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."PASS_OR_NOT" IS '允许为空
为空表示未审批
N: 未审批通过
Y: 审批通过
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."APPROVAL" IS '允许为空
审批通过的可以不用填写审批意见
审批不通过的需要填写审批意见
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."CONTACT_NUMBER" IS '可为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."CALLER_TOKEN" IS '非空，无默认值
唯一性约束
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
 
   COMMENT ON TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION"  IS '用户需要申请的资源将记录在这个表中';
--------------------------------------------------------
--  DDL for Table T_DGAP_RESOURCE_DIRECTORY
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" 
   (	"ID" VARCHAR2(64 BYTE), 
	"NAME" VARCHAR2(32 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY"."ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY"."NAME" IS '非空，无默认值，唯一约束';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY"."DESCRIPTION" IS '允许为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
 
   COMMENT ON TABLE "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY"  IS '为资源的主题归类目录，不同的资源放在相关的目录下';
--------------------------------------------------------
--  DDL for Table T_DGAP_ROLE_RESOURCE
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_ROLE_RESOURCE" 
   (	"ID" VARCHAR2(64 BYTE), 
	"ROLE_ID" VARCHAR2(64 BYTE), 
	"RESOURCE_ID" VARCHAR2(64 BYTE), 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ROLE_RESOURCE"."ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ROLE_RESOURCE"."ROLE_ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ROLE_RESOURCE"."RESOURCE_ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ROLE_RESOURCE"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ROLE_RESOURCE"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ROLE_RESOURCE"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ROLE_RESOURCE"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_ROLE_RESOURCE"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
--------------------------------------------------------
--  DDL for Table T_DGAP_WS_DAILY_STAT
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" 
   (	"ID" VARCHAR2(64 BYTE), 
	"STAT_DATE" DATE, 
	"RESOURCE_DIR" VARCHAR2(64 BYTE), 
	"WEB_SERVICE_ID" VARCHAR2(64 BYTE), 
	"WEB_SERVICE_NAME" VARCHAR2(50 BYTE), 
	"BUSSNESS_NAME" VARCHAR2(50 BYTE), 
	"CALLER_USER" VARCHAR2(20 BYTE), 
	"SUCCESS_TIMES" NUMBER(*,0), 
	"FAIL_TIMES" NUMBER(*,0), 
	"AVG_TIMECOST" NUMBER(*,0), 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."STAT_DATE" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."RESOURCE_DIR" IS '非空，无默认值
资源目录表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."WEB_SERVICE_ID" IS '非空，无默认值
资源表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."WEB_SERVICE_NAME" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."BUSSNESS_NAME" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."CALLER_USER" IS '非空，无默认值
唯一约束
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."SUCCESS_TIMES" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."FAIL_TIMES" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."AVG_TIMECOST" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_DAILY_STAT"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
 
   COMMENT ON TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT"  IS '统计每天的服务执行情况，包括成功、失败、平均耗时等信息';
--------------------------------------------------------
--  DDL for Table T_DGAP_WS_ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" 
   (	"ID" VARCHAR2(64 BYTE), 
	"RESOURCE_DIRECTORY_ID" VARCHAR2(64 BYTE), 
	"WEB_SERVICE_ID" VARCHAR2(64 BYTE), 
	"WEB_SERVICE_NAME" VARCHAR2(50 BYTE), 
	"METHOD_NAME" VARCHAR2(50 BYTE), 
	"CALLER_USER" VARCHAR2(20 BYTE), 
	"ERROR_TYPE" VARCHAR2(10 BYTE), 
	"ERROR_DESC" VARCHAR2(100 BYTE), 
	"ERROR_DATE" DATE, 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(20 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."RESOURCE_DIRECTORY_ID" IS '非空，无默认值
资源目录表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."WEB_SERVICE_ID" IS '非空，无默认值
资源表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."WEB_SERVICE_NAME" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."METHOD_NAME" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."CALLER_USER" IS '非空，无默认值
唯一约束
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."ERROR_TYPE" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."ERROR_DESC" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."ERROR_DATE" IS '非空，默认值为当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_ERROR_LOG"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
 
   COMMENT ON TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG"  IS '记录web服务出错信息日志';
--------------------------------------------------------
--  DDL for Table T_DGAP_WS_LOG
--------------------------------------------------------

  CREATE TABLE "GJZSPT"."T_DGAP_WS_LOG" 
   (	"ID" VARCHAR2(64 BYTE), 
	"RESOURCE_DIR" VARCHAR2(64 BYTE), 
	"WEB_SERVICE_ID" VARCHAR2(64 BYTE), 
	"WEB_SERVICE_NAME" VARCHAR2(50 BYTE), 
	"METHOD_NAME" VARCHAR2(50 BYTE), 
	"CALLER_USER" VARCHAR2(64 BYTE), 
	"ERROR_TYPE" VARCHAR2(10 BYTE), 
	"ERROR_DESC" VARCHAR2(100 BYTE), 
	"INVOKE_START_DATE" TIMESTAMP (6), 
	"INVOKE_END_DATE" TIMESTAMP (6), 
	"ERROR_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(64 BYTE), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE DEFAULT SYSDATE, 
	"DEL_FLAG" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"RESERVED_FIELD1" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD2" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD3" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD4" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD5" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD6" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD7" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD8" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD9" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD10" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD11" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD12" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD13" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD14" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD15" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD16" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD17" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD18" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD19" VARCHAR2(200 BYTE), 
	"RESERVED_FIELD20" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."ID" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."RESOURCE_DIR" IS '非空，无默认值
资源目录表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."WEB_SERVICE_ID" IS '非空，无默认值
资源表外键
';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."WEB_SERVICE_NAME" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."METHOD_NAME" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."CALLER_USER" IS '非空，无默认值唯一性约束';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."ERROR_TYPE" IS '允许为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."ERROR_DESC" IS '允许为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."INVOKE_START_DATE" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."INVOKE_END_DATE" IS '允许为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."ERROR_DATE" IS '允许为空';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."CREATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."CREATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."UPDATE_BY" IS '非空，无默认值';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."UPDATE_TIME" IS '非空，默认值当前时间';
 
   COMMENT ON COLUMN "GJZSPT"."T_DGAP_WS_LOG"."DEL_FLAG" IS '非空，默认值为N
N: 未删除
Y: 已删除
';
 
   COMMENT ON TABLE "GJZSPT"."T_DGAP_WS_LOG"  IS '日志类，记录web服务的调用情况';
--------------------------------------------------------
--  DDL for Index PK_T_DGAP_ALERT_CONFIG
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."PK_T_DGAP_ALERT_CONFIG" ON "GJZSPT"."T_DGAP_ALERT_CONFIG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_DGAP_ALERT_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."PK_T_DGAP_ALERT_LOG" ON "GJZSPT"."T_DGAP_ALERT_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_DGAP_ALERT_RECEIPT
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."PK_T_DGAP_ALERT_RECEIPT" ON "GJZSPT"."T_DGAP_ALERT_RECEIPT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_DGAP_RESOURCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."PK_T_DGAP_RESOURCE" ON "GJZSPT"."T_DGAP_RESOURCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_DGAP_RESOURCE_APPLICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."PK_T_DGAP_RESOURCE_APPLICATION" ON "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AK_CALLER_TOKEN_T_DGAP_R
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."AK_CALLER_TOKEN_T_DGAP_R" ON "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" ("CALLER_TOKEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_DGAP_RESOURCE_DIRECTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."PK_T_DGAP_RESOURCE_DIRECTORY" ON "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AK_NAME_T_DGAP_R
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."AK_NAME_T_DGAP_R" ON "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_DGAP_ROLE_RESOURCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."PK_T_DGAP_ROLE_RESOURCE" ON "GJZSPT"."T_DGAP_ROLE_RESOURCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_DGAP_WS_ERROR_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."PK_T_DGAP_WS_ERROR_LOG" ON "GJZSPT"."T_DGAP_WS_ERROR_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_T_DGAP_WS_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "GJZSPT"."PK_T_DGAP_WS_LOG" ON "GJZSPT"."T_DGAP_WS_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_DGAP_ALERT_CONFIG
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" ADD CONSTRAINT "PK_T_DGAP_ALERT_CONFIG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" MODIFY ("ALERT_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" MODIFY ("TARGET_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" MODIFY ("THRESHOLD" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_CONFIG" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DGAP_ALERT_LOG
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" ADD CONSTRAINT "PK_T_DGAP_ALERT_LOG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" MODIFY ("ALERT_CONFIG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" MODIFY ("TARGET_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" MODIFY ("ALERT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DGAP_ALERT_RECEIPT
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT" ADD CONSTRAINT "PK_T_DGAP_ALERT_RECEIPT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT" MODIFY ("ALERT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT" MODIFY ("RECEIPT_BY" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DGAP_RESOURCE
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE" ADD CONSTRAINT "PK_T_DGAP_RESOURCE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DGAP_RESOURCE_APPLICATION
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" ADD CONSTRAINT "AK_CALLER_TOKEN_T_DGAP_R" UNIQUE ("CALLER_TOKEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" ADD CONSTRAINT "PK_T_DGAP_RESOURCE_APPLICATION" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("EFFECTIVE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("REASON" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("CALLER_TOKEN" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DGAP_RESOURCE_DIRECTORY
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" ADD CONSTRAINT "AK_NAME_T_DGAP_R" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" ADD CONSTRAINT "PK_T_DGAP_RESOURCE_DIRECTORY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DGAP_ROLE_RESOURCE
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_ROLE_RESOURCE" ADD CONSTRAINT "PK_T_DGAP_ROLE_RESOURCE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_ROLE_RESOURCE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ROLE_RESOURCE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ROLE_RESOURCE" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ROLE_RESOURCE" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ROLE_RESOURCE" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_ROLE_RESOURCE" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DGAP_WS_DAILY_STAT
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" ADD CONSTRAINT "AK_CALLER_TOKEN_T_DGAP_M" UNIQUE ("CALLER_USER") DISABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" ADD CONSTRAINT "PK_T_DGAP_WS_DAILY_STAT" PRIMARY KEY ("ID") DISABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("STAT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("WEB_SERVICE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("WEB_SERVICE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("CALLER_USER" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("SUCCESS_TIMES" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("FAIL_TIMES" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("AVG_TIMECOST" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DGAP_WS_ERROR_LOG
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" ADD CONSTRAINT "AK_CALLER_TOKEN_T_DGAP_W" UNIQUE ("CALLER_USER") DISABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" ADD CONSTRAINT "PK_T_DGAP_WS_ERROR_LOG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("RESOURCE_DIRECTORY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("WEB_SERVICE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("WEB_SERVICE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("METHOD_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("CALLER_USER" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("ERROR_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("ERROR_DESC" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("ERROR_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DGAP_WS_LOG
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" ADD CONSTRAINT "AK_CALLER_TOKEN_A_T_DGAP_W" UNIQUE ("CALLER_USER") DISABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" ADD CONSTRAINT "PK_T_DGAP_WS_LOG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("RESOURCE_DIR" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("WEB_SERVICE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("WEB_SERVICE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("METHOD_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("CALLER_USER" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("INVOKE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_DGAP_ALERT_LOG
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" ADD CONSTRAINT "FK_T_DGAP_A_REFERENCE_T_DGAP_C" FOREIGN KEY ("ALERT_CONFIG_ID")
	  REFERENCES "GJZSPT"."T_DGAP_ALERT_CONFIG" ("ID") ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_LOG" ADD CONSTRAINT "FK_T_DGAP_A_REFERENCE_T_DGAP_R" FOREIGN KEY ("TARGET_ID")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_DGAP_ALERT_RECEIPT
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_ALERT_RECEIPT" ADD CONSTRAINT "FK_T_DGAP_A_REFERENCE_T_DGAP_A" FOREIGN KEY ("ALERT_ID")
	  REFERENCES "GJZSPT"."T_DGAP_ALERT_CONFIG" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_DGAP_RESOURCE
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE" ADD CONSTRAINT "FK_T_DGAP_R_REFERENCE_T_DGAP_R" FOREIGN KEY ("DIRECTORY_ID")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_DGAP_RESOURCE_APPLICATION
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_RESOURCE_APPLICATION" ADD CONSTRAINT "FK_T_DGAP_R_REFERENCE_T_DGAP_D" FOREIGN KEY ("RESOURCE_ID")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_DGAP_ROLE_RESOURCE
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_ROLE_RESOURCE" ADD CONSTRAINT "FK_T_DGAP_R_REFERENCE_T_DGAP_N" FOREIGN KEY ("RESOURCE_ID")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_DGAP_WS_DAILY_STAT
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" ADD CONSTRAINT "FK_T_DGAP_W_REFERENCE_T_DGAP_K" FOREIGN KEY ("RESOURCE_DIR")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" ("ID") DISABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_DAILY_STAT" ADD CONSTRAINT "FK_T_DGAP_W_REFERENCE_T_DGAP_L" FOREIGN KEY ("WEB_SERVICE_ID")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_DGAP_WS_ERROR_LOG
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" ADD CONSTRAINT "FK_T_DGAP_W_REFERENCE_T_DGAP_E" FOREIGN KEY ("RESOURCE_DIRECTORY_ID")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" ("ID") ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_ERROR_LOG" ADD CONSTRAINT "FK_T_DGAP_W_REFERENCE_T_DGAP_F" FOREIGN KEY ("WEB_SERVICE_ID")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_DGAP_WS_LOG
--------------------------------------------------------

  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" ADD CONSTRAINT "FK_T_DGAP_W_REFERENCE_T_DGAP_G" FOREIGN KEY ("RESOURCE_DIR")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE_DIRECTORY" ("ID") ENABLE;
 
  ALTER TABLE "GJZSPT"."T_DGAP_WS_LOG" ADD CONSTRAINT "FK_T_DGAP_W_REFERENCE_T_DGAP_H" FOREIGN KEY ("WEB_SERVICE_ID")
	  REFERENCES "GJZSPT"."T_DGAP_RESOURCE" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Function SQUIRREL_GET_ERROR_OFFSET
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "GJZSPT"."SQUIRREL_GET_ERROR_OFFSET" (query IN varchar2) return number authid current_user is      l_theCursor     integer default dbms_sql.open_cursor;      l_status        integer; begin          begin          dbms_sql.parse(  l_theCursor, query, dbms_sql.native );          exception                  when others then l_status := dbms_sql.last_error_position;          end;          dbms_sql.close_cursor( l_theCursor );          return l_status; end; 

/
