SELECT STATUS, GAP_STATUS FROM V$ARCHIVE_DEST_STATUS;

show parameters log_archive
SHOW PARAMETERS SPFILE

SELECT * FROM V$CONTROLFILE;
SELECT * FROM V$LOG;
SELECT * FROM V$LOGFILE;
SELECT * FROM V$LOG_HISTORY;

SELECT * FROM V$STANDBY_LOG;

SELECT * FROM V$ARCHIVED_LOG;
SELECT * FROM V$ARCHIVE_DEST;
SELECT * FROM V$ARCHIVE_PROCESSES;
SELECT * FROM V$BACKUP_REDOLOG;
SELECT * FROM V$DATAFILE;

ARCHIVE LOG LIST