#!/usr/bin/env ruby
require 'optparse'
require './rb/db'

options = {}
OptionParser.new do |opt|
	opt.on('-d','--dryrun') { |o| options[:dryrun] = o }
end.parse!

if options[:dryrun]
	db = Db.new(true,true)
else
	db = Db.new(false,true)
end

db.imp "10.0.52.1","oracle","oracle","oracle","gjzspt","gjzspt","./dmpfiles/gjzspt2017-02-14_wd.dmp"
